CREATE DATABASE EclipsePay;
USE EclipsePay;

-- USERS TABLE 
CREATE TABLE IF NOT EXISTS Users (
Id INT PRIMARY KEY AUTO_INCREMENT,
Email VARCHAR(255) UNIQUE NOT NULL,
Password VARCHAR(50) NOT NULL
);

ALTER TABLE Users AUTO_INCREMENT = 10001;